development:
  adapter: postgresql
  encoding: unicode
  database: valkyrie_dev
  pool: 5
  username: vagrant
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: valkyrie_test
  pool: 5
  username: vagrant
  password:

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
